// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Oleh Lafoks and Alisa Lafoks. Part of felitronics-toml, see LICENSE.
#pragma once

// The valid corpus documents that felitronics_toml_embed() compiled into the embedding suite, by name. The registry
// that defines embeddedCorpus() is generated by tests/CMakeLists.txt.
#include <felitronics/toml/Embedded.h>
#include <vector>

struct EmbeddedDocument
{
    const char* name;
    const felitronics::toml::embedded::Document* document;
};
std::vector<EmbeddedDocument> embeddedCorpus();
