// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Oleh Lafoks and Alisa Lafoks. Part of felitronics-toml, see LICENSE.

// felitronics_toml2cpp <input.toml> <output.h> <namespace> <name>
//
// Writes a header that holds the document as constexpr data (felitronics::toml::embedded, Embedded.h): after
//   #include "<output.h>"
// <namespace>::<name> is a constexpr embedded::Document, and <namespace>::<name>.root() the View of its root table.
// A refused document fails the build with "<input>:<line>:<column>: error: <Code>", the format compilers and IDEs
// understand. The header is only rewritten when its bytes change, so an unchanged document rebuilds nothing.
//
// Strings are spelled with octal escapes for every byte outside printable ASCII, so the header reads the same in any
// source character set. They are packed, each distinct string once, into a few literals of at most 60000 bytes:
// MSVC puts every string literal into a section of its own and allows 65279 sections in an object file, and caps a
// literal at 65535 bytes. Strings from 4000 bytes up are char arrays of their own; a string may be 65536 bytes.
#include <felitronics/toml/Toml.h>

#include <algorithm>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <map>
#include <string>
#include <vector>

using namespace felitronics::toml;

namespace
{
constexpr std::size_t kLongString = 4000;
constexpr std::size_t kPool = 60000;

std::string number (std::uint64_t n)
{
    std::string s;
    do { s.insert (s.begin(), char ('0' + n % 10)); n /= 10; } while (n != 0);
    return s;
}
std::string signedNumber (std::int64_t n)
{
    if (n == std::numeric_limits<std::int64_t>::min()) return "(-9223372036854775807 - 1)";
    return n < 0 ? "-" + number (std::uint64_t (-n)) : number (std::uint64_t (n));
}
bool identifier (std::string_view s)
{
    if (s.empty() || (s[0] >= '0' && s[0] <= '9')) return false;
    if (! std::all_of (s.begin(), s.end(), [] (char c)
        { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'; })) return false;
    constexpr std::string_view keywords[] = {
        "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor", "bool", "break", "case",
        "catch", "char", "char8_t", "char16_t", "char32_t", "class", "compl", "concept", "const", "consteval",
        "constexpr", "constinit", "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype",
        "default", "delete", "do", "double", "dynamic_cast", "else", "enum", "explicit", "export", "extern",
        "false", "float", "for", "friend", "goto", "if", "inline", "int", "long", "mutable", "namespace", "new",
        "noexcept", "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private", "protected", "public",
        "register", "reinterpret_cast", "requires", "return", "short", "signed", "sizeof", "static",
        "static_assert", "static_cast", "struct", "switch", "template", "this", "thread_local", "throw", "true",
        "try", "typedef", "typeid", "typename", "union", "unsigned", "using", "virtual", "void", "volatile",
        "wchar_t", "while", "xor", "xor_eq"
    };
    return std::find (std::begin (keywords), std::end (keywords), s) == std::end (keywords);
}
bool qualified (std::string_view s)
{
    for (std::size_t start = 0;;)
    {
        const auto end = s.find ("::", start);
        if (! identifier (s.substr (start, end == std::string_view::npos ? std::string_view::npos : end - start))) return false;
        if (end == std::string_view::npos) return true;
        start = end + 2;
    }
}

class Generator
{
public:
    std::string run (const Table& root, const std::string& input, const std::string& space, const std::string& name)
    {
        // Breadth first: a container's children are appended together, so they sit side by side in the array.
        nodes_.push_back ({});
        sources_.push_back ({ &root, nullptr, nullptr });
        nodes_[0].line = root.position.line;
        nodes_[0].column = root.position.column;
        nodes_[0].inlineStyle = false;
        for (std::size_t i = 0; i < nodes_.size(); ++i) expand (i);

        const std::string data = name + "_data";
        std::string out = "// Generated by felitronics_toml2cpp from " + input + ". Do not edit: edit the document and rebuild.\n"
                          "#pragma once\n"
                          "#include <felitronics/toml/Embedded.h>\n\n"
                          "namespace " + space + "::" + data + "\n{\n"
                          "using T = felitronics::toml::embedded::Type;\n";
        std::string pools;
        for (std::size_t i = 0; i < pools_.size(); ++i)
        {
            const auto p = "p" + number (i);
            if (pools_[i].array) out += "inline constexpr char " + p + "[] = {" + pools_[i].text + "\n};\n";
            else out += "inline constexpr char " + p + "[] =\n    \"" + pools_[i].text + "\";\n";
            pools += (i % 16 == 0 ? "\n    " : " ") + p + ",";
        }
        if (pools_.empty()) pools += "\n    nullptr,";   // an array cannot be empty; poolCount stays 0
        out += "inline constexpr const char* pools[] = {" + pools + "\n};\n";
        out += "inline constexpr felitronics::toml::embedded::Node nodes[] = {\n";
        for (const auto& n : nodes_) out += "    " + node (n) + "\n";
        out += "};\ninline constexpr std::uint32_t order[] = {";
        for (std::size_t i = 0; i < order_.size(); ++i) out += (i % 16 == 0 ? "\n    " : " ") + number (order_[i]) + ",";
        out += "\n};\n}\n\nnamespace " + space + "\n{\n"
               "inline constexpr felitronics::toml::embedded::Document " + name + " { " + data + "::nodes, " + data + "::order, "
             + number (nodes_.size()) + ", " + data + "::pools, " + number (pools_.size()) + " };\n}\n";
        return out;
    }

private:
    struct Node
    {
        std::string type = "Table";
        bool inlineStyle = false;
        std::uint8_t scale = 0;
        bool negativeZero = false;
        std::int64_t number = 0;
        std::string key, text;       // spelled as C++ initializers of embedded::Text, or empty
        std::string comment;         // a bare key, shown at the end of the line
        std::size_t first = 0, size = 0;
        std::uint32_t line = 0, column = 0, keyLine = 0, keyColumn = 0;
    };
    struct Source { const Table* table; const Array* array; const Tables* tables; };
    std::vector<Node> nodes_;
    std::vector<Source> sources_;
    std::vector<std::size_t> order_;
    // A pool is a literal of short strings side by side, or one long string as a char array.
    struct Pool { std::string text; std::size_t size = 0, width = 0; bool octal = false, array = false; };
    std::vector<Pool> pools_;
    std::optional<std::size_t> literal_;                       // the literal pool short strings go to now
    std::map<std::string, std::string, std::less<>> pooled_;   // a string's initializer, once per distinct string

    // An embedded::Text initializer: pool, offset, size. The empty string is {}.
    std::string view (std::string_view s)
    {
        if (s.empty()) return "{}";
        if (const auto found = pooled_.find (s); found != pooled_.end()) return found->second;
        std::string spelled;
        if (s.size() >= kLongString)
        {
            Pool pool;
            pool.array = true;
            for (std::size_t i = 0; i < s.size(); ++i)
                pool.text += (i % 24 == 0 ? "\n    " : " ") + std::string ("'") + escaped (static_cast<unsigned char> (s[i]), true) + "',";
            pools_.push_back (std::move (pool));
            spelled = "{ " + number (pools_.size() - 1) + ", 0, " + number (s.size()) + " }";
        }
        else
        {
            if (! literal_ || pools_[*literal_].size + s.size() >= kPool)
            {
                literal_ = pools_.size();
                pools_.emplace_back();
            }
            auto& pool = pools_[*literal_];
            spelled = "{ " + number (*literal_) + ", " + number (pool.size) + ", " + number (s.size()) + " }";
            for (const char byte : s)
            {
                const auto piece = escaped (static_cast<unsigned char> (byte), false);
                // A digit right after an octal escape starts a new literal: it is a character of its own either way,
                // but MSVC warns (C4125) when a decimal digit ends an octal escape.
                if (pool.width + piece.size() > 100 || (pool.octal && byte >= '0' && byte <= '9'))
                {
                    pool.text += pool.width + piece.size() > 100 ? "\"\n    \"" : "\" \"";
                    pool.width = 0;
                }
                pool.text += piece;
                pool.width += piece.size();
                pool.octal = piece.size() == 4 && piece[0] == '\\' && piece[1] >= '0' && piece[1] <= '3';
            }
            pool.size += s.size();
        }
        pooled_.emplace (std::string (s), spelled);
        return spelled;
    }
    // One byte, readable when it is printable ASCII and a three-digit octal escape otherwise (three digits, so a
    // digit after it cannot join it). ? is escaped against trigraphs in any older mode.
    static std::string escaped (unsigned char c, bool character)
    {
        if (c == '\\') return "\\\\";
        if (c == (character ? '\'' : '"')) return std::string ("\\") + char (c);
        if (c == '?') return "\\?";
        if (c >= 0x20 && c < 0x7F) return std::string (1, char (c));
        return { '\\', char ('0' + (c >> 6)), char ('0' + ((c >> 3) & 7)), char ('0' + (c & 7)) };
    }
    void append (const Value& v, const std::string* key, Position keyPosition)
    {
        Node n;
        Source source { nullptr, nullptr, nullptr };
        if (const auto* s = std::get_if<std::string> (&v.data)) { n.type = "String"; n.text = view (*s); }
        else if (const auto* i = std::get_if<std::int64_t> (&v.data)) { n.type = "Integer"; n.number = *i; }
        else if (const auto* d = std::get_if<Decimal> (&v.data))
        { n.type = "Decimal"; n.number = d->mantissa; n.scale = d->scale; n.negativeZero = d->negativeZero; }
        else if (const auto* b = std::get_if<bool> (&v.data)) { n.type = "Boolean"; n.number = *b ? 1 : 0; }
        else if (const auto* a = std::get_if<Array> (&v.data)) { n.type = "Array"; source.array = a; }
        else if (const auto* t = std::get_if<Table> (&v.data))
        { n.type = "Table"; n.inlineStyle = t->style == Table::Style::Inline; source.table = t; }
        else if (const auto* ts = std::get_if<Tables> (&v.data)) { n.type = "Tables"; source.tables = ts; }
        if (key != nullptr)
        {
            n.key = view (*key);
            n.keyLine = keyPosition.line;
            n.keyColumn = keyPosition.column;
            if (! key->empty() && key->size() <= 40 && std::all_of (key->begin(), key->end(), detail::bare)) n.comment = *key;
        }
        n.line = v.position.line;
        n.column = v.position.column;
        nodes_.push_back (std::move (n));
        sources_.push_back (source);
    }
    // Appends node i's children and keeps order_ one entry per node: identity, except a table's children, which
    // are listed sorted by key, as Table::find orders keys.
    void expand (std::size_t i)
    {
        const auto source = sources_[i];
        const auto first = nodes_.size();
        std::size_t size = 0;
        if (source.table != nullptr)
        {
            for (const auto& e : source.table->entries()) append (e.value, &e.key, e.keyPosition);
            size = source.table->entries().size();
        }
        else if (source.array != nullptr)
        {
            for (const auto& item : *source.array) append (item, nullptr, {});
            size = source.array->size();
        }
        else if (source.tables != nullptr)
        {
            for (const auto& element : *source.tables)
            {
                Node n;
                n.inlineStyle = element.style == Table::Style::Inline;
                n.line = element.position.line;
                n.column = element.position.column;
                nodes_.push_back (std::move (n));
                sources_.push_back ({ &element, nullptr, nullptr });
            }
            size = source.tables->size();
        }
        if (size != 0) { nodes_[i].first = first; nodes_[i].size = size; }
        for (auto k = order_.size(); k < nodes_.size(); ++k) order_.push_back (k);
        if (source.table != nullptr)
        {
            const auto& entries = source.table->entries();
            std::sort (order_.begin() + std::ptrdiff_t (first), order_.begin() + std::ptrdiff_t (first + size),
                       [&] (std::size_t x, std::size_t y) { return entries[x - first].key < entries[y - first].key; });
        }
    }
    static std::string node (const Node& n)
    {
        std::string out = "{ .type = T::" + n.type;
        if (n.inlineStyle) out += ", .inlineStyle = true";
        if (n.scale != 0) out += ", .scale = " + number (n.scale);
        if (n.negativeZero) out += ", .negativeZero = true";
        if (n.number != 0) out += ", .number = " + signedNumber (n.number);
        if (! n.key.empty() && n.key != "{}") out += ", .key = " + n.key;
        if (! n.text.empty() && n.text != "{}") out += ", .text = " + n.text;
        if (n.size != 0) out += ", .first = " + number (n.first) + ", .size = " + number (n.size);
        out += ", .line = " + number (n.line) + ", .column = " + number (n.column);
        if (n.keyLine != 0) out += ", .keyLine = " + number (n.keyLine) + ", .keyColumn = " + number (n.keyColumn);
        return out + " }," + (n.comment.empty() ? "" : "   // " + n.comment);
    }
};
}

int main (int argc, char** argv)
{
    if (argc != 5 || ! qualified (argv[3]) || ! identifier (argv[4]))
    {
        std::fprintf (stderr, "usage: felitronics_toml2cpp <input.toml> <output.h> <namespace> <name>\n"
                              "  namespace: identifiers joined by ::, name: an identifier\n");
        return 2;
    }
    const std::string input = argv[1], output = argv[2];
    std::ifstream in (input, std::ios::binary);
    if (! in) { std::fprintf (stderr, "%s: error: cannot read the file\n", input.c_str()); return 1; }
    const std::string text ((std::istreambuf_iterator<char> (in)), std::istreambuf_iterator<char>());
    const auto result = parse (text);
    if (const auto* e = std::get_if<Error> (&result))
    {
        std::fprintf (stderr, "%s:%u:%u: error: %s\n", input.c_str(), unsigned (e->line), unsigned (e->column), codeName (e->code));
        return 1;
    }
    auto base = input;
    if (const auto slash = base.find_last_of ("/\\"); slash != std::string::npos) base = base.substr (slash + 1);
    // The header stays ASCII: a file name's other bytes become '?' in the comment that names it.
    for (auto& c : base)
        if (static_cast<unsigned char> (c) < 0x20 || static_cast<unsigned char> (c) > 0x7E) c = '?';
    const auto header = Generator{}.run (std::get<Table> (result), base, argv[3], argv[4]);

    std::ifstream previous (output, std::ios::binary);
    if (previous && std::string ((std::istreambuf_iterator<char> (previous)), std::istreambuf_iterator<char>()) == header) return 0;
    previous.close();
    std::ofstream out (output, std::ios::binary | std::ios::trunc);
    out.write (header.data(), static_cast<std::streamsize> (header.size()));
    out.close();
    if (! out) { std::fprintf (stderr, "%s: error: cannot write the header\n", output.c_str()); return 1; }
    return 0;
}
